apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: internal

commonLabels:
  app.kubernetes.io/managed-by: gitlab-internal_kustomize
  app.kubernetes.io/part-of: internal

resources:
  - deployment.yaml
