apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patchesStrategicMerge:
- deployment.yaml
- resources.yaml

images:
- name: image
  newName: next/js
  newTag: "123"
