apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- path: ingress.yaml
  target:
    kind: Ingress
    name: dashboard-web

generatorOptions:
  labels:
    currently-used-by-kustomize: "true"

configMapGenerator:
- envs:
  - config.properties
  name: dashboard-config

patchesStrategicMerge:
- deployment.yaml
- resources.yaml

images:
- name: image
  newName: next/js
  newTag: "123"
